name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: zip -r $GITHUB_WORKSPACE/tab-deduper-chrome-extension.zip  $GITHUB_WORKSPACE -x "$GITHUB_WORKSPACE/.git/*"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: tab-deduper-chrome-extension
          path: ${{ github.workspace }}/tab-deduper-chrome-extension.zip
          
      - name: Release
        uses: softprops/action-gh-release@v1
        
        with:
          tag_name: 1.0.${{ github.run_number }}
          body: |
            CI Release for 1.0.${{ github.run_number }}
          files: ${{ github.workspace }}/tab-deduper-chrome-extension.zip
      
     
