name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_NUMBER: 1.0.${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: zip -r $GITHUB_WORKSPACE/tab-deduper-chrome-extension-$VERSION_NUMBER.zip  $GITHUB_WORKSPACE -x "$GITHUB_WORKSPACE/.git/*" "$GITHUB_WORKSPACE/.github/*"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: tab-deduper-chrome-extension
          path: ${{ github.workspace }}/tab-deduper-chrome-extension-${{ env.VERSION_NUMBER }}.zip
          
      - name: Release
        uses: softprops/action-gh-release@v1
        
        with:
          tag_name: ${{ env.VERSION_NUMBER }}
          body: |
            CI Release for ${{ env.VERSION_NUMBER }}
          files: ${{ github.workspace }}/tab-deduper-chrome-extension-${{ env.VERSION_NUMBER }}.zip
      
     
